plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.26.0'
    implementation group: 'org.testng', name: 'testng', version: '7.5.1'

    compileOnly 'org.projectlombok:lombok:1.18.28'
    annotationProcessor 'org.projectlombok:lombok:1.18.28'

    testCompileOnly 'org.projectlombok:lombok:1.18.28'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.28'

    implementation 'ch.qos.logback:logback-classic:1.4.14'
}
    test {
        useTestNG()
    }


task qa(type: Test) {
    useTestNG() {
        def suite = System.getProperty('suite', '')

        if (suite.equals('quick')) {
            suites 'src/test/resources/quick.xml'
        } else if (suite.equals('login')) {
            suites 'src/test/resources/login.xml'
        } else {
            suites 'src/test/resources/testng.xml'
        }
    }

    if (project.hasProperty('browser')) {
        systemProperty 'browser',

                "${browser}"

    }

    task scoupe(type:Test){
        useTestNG(){
            suites 'src/test/resources/scoupe.xml'
        }

        if (project.hasProperty('browser')) {
            systemProperty 'browser',

                    "${browser}"

        }
    }


    task team(type:Test){
        useTestNG(){
            def groups = System.getProperty('groups')
            if (groups != null) {
                includeGroups groups
            }
            suites 'src/test/resources/base.xml'
        }
    }

}